apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  strategy: {}
  template:
    metadata:
      labels:
        app: grpc-server
      annotations:
        config.linkerd.io/proxy-log-level: trace
    spec:
      containers:
      - image: teejaded/grpc-keepalive:latest
        name: grpc-server
        imagePullPolicy: Always
        command:
          - /server
          - --max-connection-age=5s
          - --max-connection-idle=120s
        env:
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: '99'
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: info
        - name: GODEBUG
          value: http2debug=2
